#person:
#  name: chin
#  age: 25
#  happy: false
#  birth: 2020/08/14
#  maps: {key: value1,key2: value2}
#  lists:
#    - code
#    - music
#    - girl
#    - boy
#    - delete
#  dog:
#    name: 泡芙
#    age: 4
server:
  port: 8083